#!/bin/bash

aria2c -c -j 16 -x 16 -s 16 --min-split-size=1M --stream-piece-selector=default -m0 --no-conf --check-integrity=true --optimize-concurrent-downloads=true --download-result=full --file-allocation=falloc "$@"
